#
# Module manifest for module 'PSMQTT'
#
# Generated by: Hannes Palmquist
#
# Generated on: 2023-11-15
#

@{
    RootModule           = 'PSMQTT.psm1'
    ModuleVersion        = '0.0.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    PowerShellVersion    = '5.1'
    GUID                 = '29cf60c3-0852-4305-b814-1523a170ce02'
    Author               = 'Hannes Palmquist'
    CompanyName          = 'GetPS'
    Copyright            = '(c) Hannes Palmquist. All rights reserved.'
    Description          = 'Powershell tools to publish and subscribe to MQTT feeds'
    NestedModules        = @()
    RequiredModules      = @()
    FunctionsToExport    = '*'
    CmdletsToExport      = '*'
    VariablesToExport    = '*'
    AliasesToExport      = '*'
    PrivateData          = @{
        PSData = @{
            LicenseUri               = 'https://github.com/hanpq/PSMQTT/blob/main/LICENSE'
            #RequireLicenseAcceptance = $false
            Prerelease               = ''
            Tags                     = @('PSEdition_Desktop', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS')
            ProjectUri               = 'https://getps.dev/modules/PSMQTT/getstarted'
            ReleaseNotes             = ''
        }
    }
}


